# Generated by Django 3.1.1 on 2020-09-24 14:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_para_1',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Last paragraph 2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_para_2',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Last paragraph 3'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_para_2',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Post paragraph 2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_para_3',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Post paragraph 3'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_quote',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Post Quote'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_quote_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Post Quote by'),
        ),
    ]
