# Generated by Django 3.1.1 on 2020-09-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_blogpost_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
