# Generated by Django 3.0.6 on 2020-09-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200924_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='last_para_1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='last_para_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_para_1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_para_2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_para_3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_quote',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_quote_by',
        ),
    ]
